export const DUMMY_USERS = [
  { id: 'usr-1', name: 'Ana García (Gerente)' },
  { id: 'usr-2', name: 'Carlos López (Finanzas)' },
  { id: 'usr-3', name: 'María Rodríguez (RRHH)' },
  { id: 'usr-4', name: 'Juan Pérez (IT)' },
  { id: 'usr-5', name: 'Elena Gómez (Operaciones)' },
  { id: 'usr-6', name: 'Luis Martínez (Ventas)' },
  { id: 'usr-7', name: 'Laura Fernández (Marketing)' },
  { id: 'usr-8', name: 'David Sánchez (Logística)' },
  { id: 'usr-9', name: 'Sofía Romero (Soporte)' },
  { id: 'usr-10', name: 'Diego Torres (Legal)' },
  { id: 'usr-11', name: 'Valentina Ruiz (Diseño)' },
  { id: 'usr-12', name: 'Andrés Castro (QA)' },
  { id: 'usr-13', name: 'Camila Navarro (Producto)' },
  { id: 'usr-14', name: 'Mateo Vargas (Desarrollo)' },
  { id: 'usr-15', name: 'Isabella Ríos (Atención al Cliente)' },
  { id: 'usr-16', name: 'Daniel Silva (Seguridad)' },
  { id: 'usr-17', name: 'Mariana Mendoza (Auditoría)' },
  { id: 'usr-18', name: 'Javier Castillo (Administración)' },
  { id: 'usr-19', name: 'Lucía Ortiz (Relaciones Públicas)' },
  { id: 'usr-20', name: 'Gabriel Herrera (Dirección)' },
];
